class _BotCommands:
    def __init__(self):
        self.StartCommand = 'start'
        self.MirrorCommand = 'megamirror'
        self.UnzipMirrorCommand = 'megaunzip'
        self.TarMirrorCommand = 'megatar'
        self.CancelMirror = 'megacancel'
        self.CancelAllCommand = 'megacancelall'
        self.ListCommand = 'list'
        self.StatusCommand = 'megastatus'
        self.AuthorizeCommand = 'megaauth'
        self.UnAuthorizeCommand = 'megaunauth'
        self.PingCommand = 'megaping'
        self.RestartCommand = 'megarestart'
        self.StatsCommand = 'megastat'
        self.HelpCommand = 'megahelp'
        self.LogCommand = 'megalog'
        self.SpeedCommand = 'megaspeedtest'
        self.CloneCommand = 'megaclone'
        self.WatchCommand = 'megawatch'
        self.TarWatchCommand = 'megatarwatch'
        self.DeleteCommand = 'megadel'
        self.UsageCommand = 'megausage'
        self.RepoCommand = 'megarepo'

BotCommands = _BotCommands()
